function:
    param_mtx: True
    tower_per_module: False
    module_per_tower: False

param_mtx:
    SC_position_file: 'sensorCell_positions.txt'
    inputdir: './input/cellPositions/'
    outputdir: './output/tower_module_mapping_array/'
    param_mtx_em_name: 'param_mtx_em.pkl'
    param_mtx_had_name: 'param_mtx_had.pkl'
    do2DHists: False

tower_per_module:
    outputdir: './output/tower_per_module/'

module_per_tower:
    bundles_file: 'allocation_20200729_1.txt'
    inputdir: './input/allocation/'
    outputdir: './output/module_per_tower/'

##########Plotting##########
plotting:
    towersPerStage1: True
    plotSCsOverTower: False
    plotSCsOverTower_singleModule: False

towersPerStage1:
    outputdir: './output/plots/towersPerStage1/'
plotSCsOverTower:
    outputdir: './output/plots/plotSCsOverTower/'
plotSCsOverTower_singleModule:
    outputdir: './output/plots/plotSCsOverTower_singleModule/'
