###########main.py#########
mainFuncs:
    silicons: False
    scintillators: False
    tower_per_module: True
    module_per_tower: False

silicons:
    N_div_silic: 8
    SCsPosition_file: 'sensorCell_positions.txt'
    inputdir: './input/cellPositions/'
    outputdir: './output/tower_module_mapping_array/'
    param_mtx_em_name: 'param_mtx_em.pkl'
    param_mtx_had_name_silic: 'param_mtx_had_silic.pkl'
    param_mtx_had_name_scint: 'param_mtx_had_scint.pkl'
    do2DHists: False

scintillators:
    N_div_scint: 16
    TCsPosition_file: 'TCPositions_sctintillator.csv'

tower_per_module:
    outputdir: './output/tower_per_module/'

module_per_tower:
    bundles_file: 'allocation_20210616_14bundles.txt'
    inputdir: './input/allocation/'
    outputdir: './output/module_per_tower/'

##########plotter.py##########
plotterFuncs:
    towersPerStage1: True
    plotSCsOverTower: False
    plotSCsOverTower_singleModule: False
    TotNumOfSumsPerTower: False

towersPerStage1:
    outputdir: './output/plots/towersPerStage1/'
plotSCsOverTower:
    outputdir: './output/plots/plotSCsOverTower/'
plotSCsOverTower_singleModule:
    outputdir: './output/plots/plotSCsOverTower_singleModule/'
TotNumOfSumsPerTower:
    outputdir: './output/plots/TotNumOfSumsPerTower/'

histRange:
    etaBinStep: 0.0870
    minBinEta: 14
    maxBinEta: 36
    phiBinStep: 2*math.pi/72
    minBinPhi: -5
    maxBinPhi: 28
